package test.model;

import java.math.BigDecimal;
import java.util.Date;

public class FinancIncomeDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financ_income.financ_income_id
     *
     * @mbggenerated
     */
    private Integer financIncomeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financ_income.financ_income_uuid
     *
     * @mbggenerated
     */
    private String financIncomeUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financ_income.property_value_transfer_uuid
     *
     * @mbggenerated
     */
    private String propertyValueTransferUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financ_income.product_order_uuid
     *
     * @mbggenerated
     */
    private String productOrderUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financ_income.income_property_uuid
     *
     * @mbggenerated
     */
    private String incomePropertyUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financ_income.income_time
     *
     * @mbggenerated
     */
    private Date incomeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financ_income.income_amount
     *
     * @mbggenerated
     */
    private BigDecimal incomeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financ_income.create_user_uuid
     *
     * @mbggenerated
     */
    private String createUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financ_income.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financ_income.last_update_user_uuid
     *
     * @mbggenerated
     */
    private String lastUpdateUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financ_income.last_update_time
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financ_income.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financ_income.financ_income_id
     *
     * @return the value of financ_income.financ_income_id
     *
     * @mbggenerated
     */
    public Integer getFinancIncomeId() {
        return financIncomeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financ_income.financ_income_id
     *
     * @param financIncomeId the value for financ_income.financ_income_id
     *
     * @mbggenerated
     */
    public void setFinancIncomeId(Integer financIncomeId) {
        this.financIncomeId = financIncomeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financ_income.financ_income_uuid
     *
     * @return the value of financ_income.financ_income_uuid
     *
     * @mbggenerated
     */
    public String getFinancIncomeUuid() {
        return financIncomeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financ_income.financ_income_uuid
     *
     * @param financIncomeUuid the value for financ_income.financ_income_uuid
     *
     * @mbggenerated
     */
    public void setFinancIncomeUuid(String financIncomeUuid) {
        this.financIncomeUuid = financIncomeUuid == null ? null : financIncomeUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financ_income.property_value_transfer_uuid
     *
     * @return the value of financ_income.property_value_transfer_uuid
     *
     * @mbggenerated
     */
    public String getPropertyValueTransferUuid() {
        return propertyValueTransferUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financ_income.property_value_transfer_uuid
     *
     * @param propertyValueTransferUuid the value for financ_income.property_value_transfer_uuid
     *
     * @mbggenerated
     */
    public void setPropertyValueTransferUuid(String propertyValueTransferUuid) {
        this.propertyValueTransferUuid = propertyValueTransferUuid == null ? null : propertyValueTransferUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financ_income.product_order_uuid
     *
     * @return the value of financ_income.product_order_uuid
     *
     * @mbggenerated
     */
    public String getProductOrderUuid() {
        return productOrderUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financ_income.product_order_uuid
     *
     * @param productOrderUuid the value for financ_income.product_order_uuid
     *
     * @mbggenerated
     */
    public void setProductOrderUuid(String productOrderUuid) {
        this.productOrderUuid = productOrderUuid == null ? null : productOrderUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financ_income.income_property_uuid
     *
     * @return the value of financ_income.income_property_uuid
     *
     * @mbggenerated
     */
    public String getIncomePropertyUuid() {
        return incomePropertyUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financ_income.income_property_uuid
     *
     * @param incomePropertyUuid the value for financ_income.income_property_uuid
     *
     * @mbggenerated
     */
    public void setIncomePropertyUuid(String incomePropertyUuid) {
        this.incomePropertyUuid = incomePropertyUuid == null ? null : incomePropertyUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financ_income.income_time
     *
     * @return the value of financ_income.income_time
     *
     * @mbggenerated
     */
    public Date getIncomeTime() {
        return incomeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financ_income.income_time
     *
     * @param incomeTime the value for financ_income.income_time
     *
     * @mbggenerated
     */
    public void setIncomeTime(Date incomeTime) {
        this.incomeTime = incomeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financ_income.income_amount
     *
     * @return the value of financ_income.income_amount
     *
     * @mbggenerated
     */
    public BigDecimal getIncomeAmount() {
        return incomeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financ_income.income_amount
     *
     * @param incomeAmount the value for financ_income.income_amount
     *
     * @mbggenerated
     */
    public void setIncomeAmount(BigDecimal incomeAmount) {
        this.incomeAmount = incomeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financ_income.create_user_uuid
     *
     * @return the value of financ_income.create_user_uuid
     *
     * @mbggenerated
     */
    public String getCreateUserUuid() {
        return createUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financ_income.create_user_uuid
     *
     * @param createUserUuid the value for financ_income.create_user_uuid
     *
     * @mbggenerated
     */
    public void setCreateUserUuid(String createUserUuid) {
        this.createUserUuid = createUserUuid == null ? null : createUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financ_income.create_time
     *
     * @return the value of financ_income.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financ_income.create_time
     *
     * @param createTime the value for financ_income.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financ_income.last_update_user_uuid
     *
     * @return the value of financ_income.last_update_user_uuid
     *
     * @mbggenerated
     */
    public String getLastUpdateUserUuid() {
        return lastUpdateUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financ_income.last_update_user_uuid
     *
     * @param lastUpdateUserUuid the value for financ_income.last_update_user_uuid
     *
     * @mbggenerated
     */
    public void setLastUpdateUserUuid(String lastUpdateUserUuid) {
        this.lastUpdateUserUuid = lastUpdateUserUuid == null ? null : lastUpdateUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financ_income.last_update_time
     *
     * @return the value of financ_income.last_update_time
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financ_income.last_update_time
     *
     * @param lastUpdateTime the value for financ_income.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financ_income.del_flag
     *
     * @return the value of financ_income.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financ_income.del_flag
     *
     * @param delFlag the value for financ_income.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}