package test.model;

import java.util.Date;

public class PartyDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.party_id
     *
     * @mbggenerated
     */
    private Integer partyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.party_uuid
     *
     * @mbggenerated
     */
    private String partyUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.party_type
     *
     * @mbggenerated
     */
    private Integer partyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.main_ident
     *
     * @mbggenerated
     */
    private String mainIdent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.party_name
     *
     * @mbggenerated
     */
    private String partyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.etl_data_source
     *
     * @mbggenerated
     */
    private String etlDataSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.etl_uniq_id
     *
     * @mbggenerated
     */
    private String etlUniqId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.create_user_uuid
     *
     * @mbggenerated
     */
    private String createUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.last_update_user_uuid
     *
     * @mbggenerated
     */
    private String lastUpdateUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.last_update_time
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.party_id
     *
     * @return the value of party.party_id
     *
     * @mbggenerated
     */
    public Integer getPartyId() {
        return partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.party_id
     *
     * @param partyId the value for party.party_id
     *
     * @mbggenerated
     */
    public void setPartyId(Integer partyId) {
        this.partyId = partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.party_uuid
     *
     * @return the value of party.party_uuid
     *
     * @mbggenerated
     */
    public String getPartyUuid() {
        return partyUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.party_uuid
     *
     * @param partyUuid the value for party.party_uuid
     *
     * @mbggenerated
     */
    public void setPartyUuid(String partyUuid) {
        this.partyUuid = partyUuid == null ? null : partyUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.party_type
     *
     * @return the value of party.party_type
     *
     * @mbggenerated
     */
    public Integer getPartyType() {
        return partyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.party_type
     *
     * @param partyType the value for party.party_type
     *
     * @mbggenerated
     */
    public void setPartyType(Integer partyType) {
        this.partyType = partyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.main_ident
     *
     * @return the value of party.main_ident
     *
     * @mbggenerated
     */
    public String getMainIdent() {
        return mainIdent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.main_ident
     *
     * @param mainIdent the value for party.main_ident
     *
     * @mbggenerated
     */
    public void setMainIdent(String mainIdent) {
        this.mainIdent = mainIdent == null ? null : mainIdent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.party_name
     *
     * @return the value of party.party_name
     *
     * @mbggenerated
     */
    public String getPartyName() {
        return partyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.party_name
     *
     * @param partyName the value for party.party_name
     *
     * @mbggenerated
     */
    public void setPartyName(String partyName) {
        this.partyName = partyName == null ? null : partyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.etl_data_source
     *
     * @return the value of party.etl_data_source
     *
     * @mbggenerated
     */
    public String getEtlDataSource() {
        return etlDataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.etl_data_source
     *
     * @param etlDataSource the value for party.etl_data_source
     *
     * @mbggenerated
     */
    public void setEtlDataSource(String etlDataSource) {
        this.etlDataSource = etlDataSource == null ? null : etlDataSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.etl_uniq_id
     *
     * @return the value of party.etl_uniq_id
     *
     * @mbggenerated
     */
    public String getEtlUniqId() {
        return etlUniqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.etl_uniq_id
     *
     * @param etlUniqId the value for party.etl_uniq_id
     *
     * @mbggenerated
     */
    public void setEtlUniqId(String etlUniqId) {
        this.etlUniqId = etlUniqId == null ? null : etlUniqId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.create_user_uuid
     *
     * @return the value of party.create_user_uuid
     *
     * @mbggenerated
     */
    public String getCreateUserUuid() {
        return createUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.create_user_uuid
     *
     * @param createUserUuid the value for party.create_user_uuid
     *
     * @mbggenerated
     */
    public void setCreateUserUuid(String createUserUuid) {
        this.createUserUuid = createUserUuid == null ? null : createUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.create_time
     *
     * @return the value of party.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.create_time
     *
     * @param createTime the value for party.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.last_update_user_uuid
     *
     * @return the value of party.last_update_user_uuid
     *
     * @mbggenerated
     */
    public String getLastUpdateUserUuid() {
        return lastUpdateUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.last_update_user_uuid
     *
     * @param lastUpdateUserUuid the value for party.last_update_user_uuid
     *
     * @mbggenerated
     */
    public void setLastUpdateUserUuid(String lastUpdateUserUuid) {
        this.lastUpdateUserUuid = lastUpdateUserUuid == null ? null : lastUpdateUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.last_update_time
     *
     * @return the value of party.last_update_time
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.last_update_time
     *
     * @param lastUpdateTime the value for party.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.del_flag
     *
     * @return the value of party.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.del_flag
     *
     * @param delFlag the value for party.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}