package test.model;

import java.util.Date;

public class PartyVisitLogDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_visit_log.party_visit_log_id
     *
     * @mbggenerated
     */
    private Integer partyVisitLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_visit_log.dev_id
     *
     * @mbggenerated
     */
    private String devId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_visit_log.dev_type
     *
     * @mbggenerated
     */
    private String devType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_visit_log.dev_mac
     *
     * @mbggenerated
     */
    private String devMac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_visit_log.visit_source_code
     *
     * @mbggenerated
     */
    private String visitSourceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_visit_log.session_id
     *
     * @mbggenerated
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_visit_log.visit_ip
     *
     * @mbggenerated
     */
    private String visitIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_visit_log.visit_time
     *
     * @mbggenerated
     */
    private Date visitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_visit_log.visit_longitude
     *
     * @mbggenerated
     */
    private String visitLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_visit_log.visit_latitude
     *
     * @mbggenerated
     */
    private String visitLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_visit_log.visit_addr
     *
     * @mbggenerated
     */
    private String visitAddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_visit_log.party_visit_log_id
     *
     * @return the value of party_visit_log.party_visit_log_id
     *
     * @mbggenerated
     */
    public Integer getPartyVisitLogId() {
        return partyVisitLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_visit_log.party_visit_log_id
     *
     * @param partyVisitLogId the value for party_visit_log.party_visit_log_id
     *
     * @mbggenerated
     */
    public void setPartyVisitLogId(Integer partyVisitLogId) {
        this.partyVisitLogId = partyVisitLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_visit_log.dev_id
     *
     * @return the value of party_visit_log.dev_id
     *
     * @mbggenerated
     */
    public String getDevId() {
        return devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_visit_log.dev_id
     *
     * @param devId the value for party_visit_log.dev_id
     *
     * @mbggenerated
     */
    public void setDevId(String devId) {
        this.devId = devId == null ? null : devId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_visit_log.dev_type
     *
     * @return the value of party_visit_log.dev_type
     *
     * @mbggenerated
     */
    public String getDevType() {
        return devType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_visit_log.dev_type
     *
     * @param devType the value for party_visit_log.dev_type
     *
     * @mbggenerated
     */
    public void setDevType(String devType) {
        this.devType = devType == null ? null : devType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_visit_log.dev_mac
     *
     * @return the value of party_visit_log.dev_mac
     *
     * @mbggenerated
     */
    public String getDevMac() {
        return devMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_visit_log.dev_mac
     *
     * @param devMac the value for party_visit_log.dev_mac
     *
     * @mbggenerated
     */
    public void setDevMac(String devMac) {
        this.devMac = devMac == null ? null : devMac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_visit_log.visit_source_code
     *
     * @return the value of party_visit_log.visit_source_code
     *
     * @mbggenerated
     */
    public String getVisitSourceCode() {
        return visitSourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_visit_log.visit_source_code
     *
     * @param visitSourceCode the value for party_visit_log.visit_source_code
     *
     * @mbggenerated
     */
    public void setVisitSourceCode(String visitSourceCode) {
        this.visitSourceCode = visitSourceCode == null ? null : visitSourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_visit_log.session_id
     *
     * @return the value of party_visit_log.session_id
     *
     * @mbggenerated
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_visit_log.session_id
     *
     * @param sessionId the value for party_visit_log.session_id
     *
     * @mbggenerated
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId == null ? null : sessionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_visit_log.visit_ip
     *
     * @return the value of party_visit_log.visit_ip
     *
     * @mbggenerated
     */
    public String getVisitIp() {
        return visitIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_visit_log.visit_ip
     *
     * @param visitIp the value for party_visit_log.visit_ip
     *
     * @mbggenerated
     */
    public void setVisitIp(String visitIp) {
        this.visitIp = visitIp == null ? null : visitIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_visit_log.visit_time
     *
     * @return the value of party_visit_log.visit_time
     *
     * @mbggenerated
     */
    public Date getVisitTime() {
        return visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_visit_log.visit_time
     *
     * @param visitTime the value for party_visit_log.visit_time
     *
     * @mbggenerated
     */
    public void setVisitTime(Date visitTime) {
        this.visitTime = visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_visit_log.visit_longitude
     *
     * @return the value of party_visit_log.visit_longitude
     *
     * @mbggenerated
     */
    public String getVisitLongitude() {
        return visitLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_visit_log.visit_longitude
     *
     * @param visitLongitude the value for party_visit_log.visit_longitude
     *
     * @mbggenerated
     */
    public void setVisitLongitude(String visitLongitude) {
        this.visitLongitude = visitLongitude == null ? null : visitLongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_visit_log.visit_latitude
     *
     * @return the value of party_visit_log.visit_latitude
     *
     * @mbggenerated
     */
    public String getVisitLatitude() {
        return visitLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_visit_log.visit_latitude
     *
     * @param visitLatitude the value for party_visit_log.visit_latitude
     *
     * @mbggenerated
     */
    public void setVisitLatitude(String visitLatitude) {
        this.visitLatitude = visitLatitude == null ? null : visitLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_visit_log.visit_addr
     *
     * @return the value of party_visit_log.visit_addr
     *
     * @mbggenerated
     */
    public String getVisitAddr() {
        return visitAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_visit_log.visit_addr
     *
     * @param visitAddr the value for party_visit_log.visit_addr
     *
     * @mbggenerated
     */
    public void setVisitAddr(String visitAddr) {
        this.visitAddr = visitAddr == null ? null : visitAddr.trim();
    }
}