package test.model;

import java.math.BigDecimal;
import java.util.Date;

public class PartyOrgDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.party_org_id
     *
     * @mbggenerated
     */
    private Integer partyOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.party_org_uuid
     *
     * @mbggenerated
     */
    private String partyOrgUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.party_uuid
     *
     * @mbggenerated
     */
    private String partyUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.org_name
     *
     * @mbggenerated
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.org_shortname
     *
     * @mbggenerated
     */
    private String orgShortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.reg_number
     *
     * @mbggenerated
     */
    private String regNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.org_code
     *
     * @mbggenerated
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.org_type
     *
     * @mbggenerated
     */
    private String orgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.enterprise_type
     *
     * @mbggenerated
     */
    private String enterpriseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.economic_type
     *
     * @mbggenerated
     */
    private String economicType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.reg_capital
     *
     * @mbggenerated
     */
    private BigDecimal regCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.reg_authority
     *
     * @mbggenerated
     */
    private String regAuthority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.reg_date
     *
     * @mbggenerated
     */
    private Date regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.code_cert_date
     *
     * @mbggenerated
     */
    private Date codeCertDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.code_invalid_date
     *
     * @mbggenerated
     */
    private Date codeInvalidDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.postcode
     *
     * @mbggenerated
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.main_business
     *
     * @mbggenerated
     */
    private String mainBusiness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.fax
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.people_total
     *
     * @mbggenerated
     */
    private Integer peopleTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.auto_assign_flag
     *
     * @mbggenerated
     */
    private Integer autoAssignFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.org_status
     *
     * @mbggenerated
     */
    private Integer orgStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.create_user_uuid
     *
     * @mbggenerated
     */
    private String createUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.last_update_user_uuid
     *
     * @mbggenerated
     */
    private String lastUpdateUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.last_update_time
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_org.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.party_org_id
     *
     * @return the value of party_org.party_org_id
     *
     * @mbggenerated
     */
    public Integer getPartyOrgId() {
        return partyOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.party_org_id
     *
     * @param partyOrgId the value for party_org.party_org_id
     *
     * @mbggenerated
     */
    public void setPartyOrgId(Integer partyOrgId) {
        this.partyOrgId = partyOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.party_org_uuid
     *
     * @return the value of party_org.party_org_uuid
     *
     * @mbggenerated
     */
    public String getPartyOrgUuid() {
        return partyOrgUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.party_org_uuid
     *
     * @param partyOrgUuid the value for party_org.party_org_uuid
     *
     * @mbggenerated
     */
    public void setPartyOrgUuid(String partyOrgUuid) {
        this.partyOrgUuid = partyOrgUuid == null ? null : partyOrgUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.party_uuid
     *
     * @return the value of party_org.party_uuid
     *
     * @mbggenerated
     */
    public String getPartyUuid() {
        return partyUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.party_uuid
     *
     * @param partyUuid the value for party_org.party_uuid
     *
     * @mbggenerated
     */
    public void setPartyUuid(String partyUuid) {
        this.partyUuid = partyUuid == null ? null : partyUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.org_name
     *
     * @return the value of party_org.org_name
     *
     * @mbggenerated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.org_name
     *
     * @param orgName the value for party_org.org_name
     *
     * @mbggenerated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.org_shortname
     *
     * @return the value of party_org.org_shortname
     *
     * @mbggenerated
     */
    public String getOrgShortname() {
        return orgShortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.org_shortname
     *
     * @param orgShortname the value for party_org.org_shortname
     *
     * @mbggenerated
     */
    public void setOrgShortname(String orgShortname) {
        this.orgShortname = orgShortname == null ? null : orgShortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.reg_number
     *
     * @return the value of party_org.reg_number
     *
     * @mbggenerated
     */
    public String getRegNumber() {
        return regNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.reg_number
     *
     * @param regNumber the value for party_org.reg_number
     *
     * @mbggenerated
     */
    public void setRegNumber(String regNumber) {
        this.regNumber = regNumber == null ? null : regNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.org_code
     *
     * @return the value of party_org.org_code
     *
     * @mbggenerated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.org_code
     *
     * @param orgCode the value for party_org.org_code
     *
     * @mbggenerated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.org_type
     *
     * @return the value of party_org.org_type
     *
     * @mbggenerated
     */
    public String getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.org_type
     *
     * @param orgType the value for party_org.org_type
     *
     * @mbggenerated
     */
    public void setOrgType(String orgType) {
        this.orgType = orgType == null ? null : orgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.enterprise_type
     *
     * @return the value of party_org.enterprise_type
     *
     * @mbggenerated
     */
    public String getEnterpriseType() {
        return enterpriseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.enterprise_type
     *
     * @param enterpriseType the value for party_org.enterprise_type
     *
     * @mbggenerated
     */
    public void setEnterpriseType(String enterpriseType) {
        this.enterpriseType = enterpriseType == null ? null : enterpriseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.economic_type
     *
     * @return the value of party_org.economic_type
     *
     * @mbggenerated
     */
    public String getEconomicType() {
        return economicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.economic_type
     *
     * @param economicType the value for party_org.economic_type
     *
     * @mbggenerated
     */
    public void setEconomicType(String economicType) {
        this.economicType = economicType == null ? null : economicType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.reg_capital
     *
     * @return the value of party_org.reg_capital
     *
     * @mbggenerated
     */
    public BigDecimal getRegCapital() {
        return regCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.reg_capital
     *
     * @param regCapital the value for party_org.reg_capital
     *
     * @mbggenerated
     */
    public void setRegCapital(BigDecimal regCapital) {
        this.regCapital = regCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.reg_authority
     *
     * @return the value of party_org.reg_authority
     *
     * @mbggenerated
     */
    public String getRegAuthority() {
        return regAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.reg_authority
     *
     * @param regAuthority the value for party_org.reg_authority
     *
     * @mbggenerated
     */
    public void setRegAuthority(String regAuthority) {
        this.regAuthority = regAuthority == null ? null : regAuthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.reg_date
     *
     * @return the value of party_org.reg_date
     *
     * @mbggenerated
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.reg_date
     *
     * @param regDate the value for party_org.reg_date
     *
     * @mbggenerated
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.code_cert_date
     *
     * @return the value of party_org.code_cert_date
     *
     * @mbggenerated
     */
    public Date getCodeCertDate() {
        return codeCertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.code_cert_date
     *
     * @param codeCertDate the value for party_org.code_cert_date
     *
     * @mbggenerated
     */
    public void setCodeCertDate(Date codeCertDate) {
        this.codeCertDate = codeCertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.code_invalid_date
     *
     * @return the value of party_org.code_invalid_date
     *
     * @mbggenerated
     */
    public Date getCodeInvalidDate() {
        return codeInvalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.code_invalid_date
     *
     * @param codeInvalidDate the value for party_org.code_invalid_date
     *
     * @mbggenerated
     */
    public void setCodeInvalidDate(Date codeInvalidDate) {
        this.codeInvalidDate = codeInvalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.postcode
     *
     * @return the value of party_org.postcode
     *
     * @mbggenerated
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.postcode
     *
     * @param postcode the value for party_org.postcode
     *
     * @mbggenerated
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.tel
     *
     * @return the value of party_org.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.tel
     *
     * @param tel the value for party_org.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.main_business
     *
     * @return the value of party_org.main_business
     *
     * @mbggenerated
     */
    public String getMainBusiness() {
        return mainBusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.main_business
     *
     * @param mainBusiness the value for party_org.main_business
     *
     * @mbggenerated
     */
    public void setMainBusiness(String mainBusiness) {
        this.mainBusiness = mainBusiness == null ? null : mainBusiness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.fax
     *
     * @return the value of party_org.fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.fax
     *
     * @param fax the value for party_org.fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.people_total
     *
     * @return the value of party_org.people_total
     *
     * @mbggenerated
     */
    public Integer getPeopleTotal() {
        return peopleTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.people_total
     *
     * @param peopleTotal the value for party_org.people_total
     *
     * @mbggenerated
     */
    public void setPeopleTotal(Integer peopleTotal) {
        this.peopleTotal = peopleTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.auto_assign_flag
     *
     * @return the value of party_org.auto_assign_flag
     *
     * @mbggenerated
     */
    public Integer getAutoAssignFlag() {
        return autoAssignFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.auto_assign_flag
     *
     * @param autoAssignFlag the value for party_org.auto_assign_flag
     *
     * @mbggenerated
     */
    public void setAutoAssignFlag(Integer autoAssignFlag) {
        this.autoAssignFlag = autoAssignFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.org_status
     *
     * @return the value of party_org.org_status
     *
     * @mbggenerated
     */
    public Integer getOrgStatus() {
        return orgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.org_status
     *
     * @param orgStatus the value for party_org.org_status
     *
     * @mbggenerated
     */
    public void setOrgStatus(Integer orgStatus) {
        this.orgStatus = orgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.create_user_uuid
     *
     * @return the value of party_org.create_user_uuid
     *
     * @mbggenerated
     */
    public String getCreateUserUuid() {
        return createUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.create_user_uuid
     *
     * @param createUserUuid the value for party_org.create_user_uuid
     *
     * @mbggenerated
     */
    public void setCreateUserUuid(String createUserUuid) {
        this.createUserUuid = createUserUuid == null ? null : createUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.create_time
     *
     * @return the value of party_org.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.create_time
     *
     * @param createTime the value for party_org.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.last_update_user_uuid
     *
     * @return the value of party_org.last_update_user_uuid
     *
     * @mbggenerated
     */
    public String getLastUpdateUserUuid() {
        return lastUpdateUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.last_update_user_uuid
     *
     * @param lastUpdateUserUuid the value for party_org.last_update_user_uuid
     *
     * @mbggenerated
     */
    public void setLastUpdateUserUuid(String lastUpdateUserUuid) {
        this.lastUpdateUserUuid = lastUpdateUserUuid == null ? null : lastUpdateUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.last_update_time
     *
     * @return the value of party_org.last_update_time
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.last_update_time
     *
     * @param lastUpdateTime the value for party_org.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_org.del_flag
     *
     * @return the value of party_org.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_org.del_flag
     *
     * @param delFlag the value for party_org.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}