package test.model;

import java.math.BigDecimal;
import java.util.Date;

public class ProductDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_uuid
     *
     * @mbggenerated
     */
    private String productUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.owner_party_uuid
     *
     * @mbggenerated
     */
    private String ownerPartyUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_no
     *
     * @mbggenerated
     */
    private String productNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.expected_yield
     *
     * @mbggenerated
     */
    private BigDecimal expectedYield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.preserve_type
     *
     * @mbggenerated
     */
    private String preserveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.investment_cycle
     *
     * @mbggenerated
     */
    private Integer investmentCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.min_amount
     *
     * @mbggenerated
     */
    private BigDecimal minAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.incr_amount
     *
     * @mbggenerated
     */
    private BigDecimal incrAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.rsk_level
     *
     * @mbggenerated
     */
    private String rskLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.invest_field
     *
     * @mbggenerated
     */
    private String investField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_user_uuid
     *
     * @mbggenerated
     */
    private String createUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.last_update_user_uuid
     *
     * @mbggenerated
     */
    private String lastUpdateUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.last_update_time
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param productId the value for product.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_uuid
     *
     * @return the value of product.product_uuid
     *
     * @mbggenerated
     */
    public String getProductUuid() {
        return productUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_uuid
     *
     * @param productUuid the value for product.product_uuid
     *
     * @mbggenerated
     */
    public void setProductUuid(String productUuid) {
        this.productUuid = productUuid == null ? null : productUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.owner_party_uuid
     *
     * @return the value of product.owner_party_uuid
     *
     * @mbggenerated
     */
    public String getOwnerPartyUuid() {
        return ownerPartyUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.owner_party_uuid
     *
     * @param ownerPartyUuid the value for product.owner_party_uuid
     *
     * @mbggenerated
     */
    public void setOwnerPartyUuid(String ownerPartyUuid) {
        this.ownerPartyUuid = ownerPartyUuid == null ? null : ownerPartyUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_no
     *
     * @return the value of product.product_no
     *
     * @mbggenerated
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_no
     *
     * @param productNo the value for product.product_no
     *
     * @mbggenerated
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.expected_yield
     *
     * @return the value of product.expected_yield
     *
     * @mbggenerated
     */
    public BigDecimal getExpectedYield() {
        return expectedYield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.expected_yield
     *
     * @param expectedYield the value for product.expected_yield
     *
     * @mbggenerated
     */
    public void setExpectedYield(BigDecimal expectedYield) {
        this.expectedYield = expectedYield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.preserve_type
     *
     * @return the value of product.preserve_type
     *
     * @mbggenerated
     */
    public String getPreserveType() {
        return preserveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.preserve_type
     *
     * @param preserveType the value for product.preserve_type
     *
     * @mbggenerated
     */
    public void setPreserveType(String preserveType) {
        this.preserveType = preserveType == null ? null : preserveType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.investment_cycle
     *
     * @return the value of product.investment_cycle
     *
     * @mbggenerated
     */
    public Integer getInvestmentCycle() {
        return investmentCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.investment_cycle
     *
     * @param investmentCycle the value for product.investment_cycle
     *
     * @mbggenerated
     */
    public void setInvestmentCycle(Integer investmentCycle) {
        this.investmentCycle = investmentCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.min_amount
     *
     * @return the value of product.min_amount
     *
     * @mbggenerated
     */
    public BigDecimal getMinAmount() {
        return minAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.min_amount
     *
     * @param minAmount the value for product.min_amount
     *
     * @mbggenerated
     */
    public void setMinAmount(BigDecimal minAmount) {
        this.minAmount = minAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.incr_amount
     *
     * @return the value of product.incr_amount
     *
     * @mbggenerated
     */
    public BigDecimal getIncrAmount() {
        return incrAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.incr_amount
     *
     * @param incrAmount the value for product.incr_amount
     *
     * @mbggenerated
     */
    public void setIncrAmount(BigDecimal incrAmount) {
        this.incrAmount = incrAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.rsk_level
     *
     * @return the value of product.rsk_level
     *
     * @mbggenerated
     */
    public String getRskLevel() {
        return rskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.rsk_level
     *
     * @param rskLevel the value for product.rsk_level
     *
     * @mbggenerated
     */
    public void setRskLevel(String rskLevel) {
        this.rskLevel = rskLevel == null ? null : rskLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.invest_field
     *
     * @return the value of product.invest_field
     *
     * @mbggenerated
     */
    public String getInvestField() {
        return investField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.invest_field
     *
     * @param investField the value for product.invest_field
     *
     * @mbggenerated
     */
    public void setInvestField(String investField) {
        this.investField = investField == null ? null : investField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_user_uuid
     *
     * @return the value of product.create_user_uuid
     *
     * @mbggenerated
     */
    public String getCreateUserUuid() {
        return createUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_user_uuid
     *
     * @param createUserUuid the value for product.create_user_uuid
     *
     * @mbggenerated
     */
    public void setCreateUserUuid(String createUserUuid) {
        this.createUserUuid = createUserUuid == null ? null : createUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_time
     *
     * @return the value of product.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_time
     *
     * @param createTime the value for product.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.last_update_user_uuid
     *
     * @return the value of product.last_update_user_uuid
     *
     * @mbggenerated
     */
    public String getLastUpdateUserUuid() {
        return lastUpdateUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.last_update_user_uuid
     *
     * @param lastUpdateUserUuid the value for product.last_update_user_uuid
     *
     * @mbggenerated
     */
    public void setLastUpdateUserUuid(String lastUpdateUserUuid) {
        this.lastUpdateUserUuid = lastUpdateUserUuid == null ? null : lastUpdateUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.last_update_time
     *
     * @return the value of product.last_update_time
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.last_update_time
     *
     * @param lastUpdateTime the value for product.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.del_flag
     *
     * @return the value of product.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.del_flag
     *
     * @param delFlag the value for product.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}