package test.model;

import java.util.Date;

public class ProofMatType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat_type.proof_mat_type_id
     *
     * @mbggenerated
     */
    private Integer proofMatTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat_type.proof_mat_type_uuid
     *
     * @mbggenerated
     */
    private String proofMatTypeUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat_type.mat_type_name
     *
     * @mbggenerated
     */
    private String matTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat_type.mat_type_code
     *
     * @mbggenerated
     */
    private String matTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat_type.use_scope
     *
     * @mbggenerated
     */
    private String useScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat_type.create_user_uuid
     *
     * @mbggenerated
     */
    private String createUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat_type.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat_type.last_update_user_uuid
     *
     * @mbggenerated
     */
    private String lastUpdateUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat_type.last_update_time
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat_type.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat_type.proof_mat_type_id
     *
     * @return the value of proof_mat_type.proof_mat_type_id
     *
     * @mbggenerated
     */
    public Integer getProofMatTypeId() {
        return proofMatTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat_type.proof_mat_type_id
     *
     * @param proofMatTypeId the value for proof_mat_type.proof_mat_type_id
     *
     * @mbggenerated
     */
    public void setProofMatTypeId(Integer proofMatTypeId) {
        this.proofMatTypeId = proofMatTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat_type.proof_mat_type_uuid
     *
     * @return the value of proof_mat_type.proof_mat_type_uuid
     *
     * @mbggenerated
     */
    public String getProofMatTypeUuid() {
        return proofMatTypeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat_type.proof_mat_type_uuid
     *
     * @param proofMatTypeUuid the value for proof_mat_type.proof_mat_type_uuid
     *
     * @mbggenerated
     */
    public void setProofMatTypeUuid(String proofMatTypeUuid) {
        this.proofMatTypeUuid = proofMatTypeUuid == null ? null : proofMatTypeUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat_type.mat_type_name
     *
     * @return the value of proof_mat_type.mat_type_name
     *
     * @mbggenerated
     */
    public String getMatTypeName() {
        return matTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat_type.mat_type_name
     *
     * @param matTypeName the value for proof_mat_type.mat_type_name
     *
     * @mbggenerated
     */
    public void setMatTypeName(String matTypeName) {
        this.matTypeName = matTypeName == null ? null : matTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat_type.mat_type_code
     *
     * @return the value of proof_mat_type.mat_type_code
     *
     * @mbggenerated
     */
    public String getMatTypeCode() {
        return matTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat_type.mat_type_code
     *
     * @param matTypeCode the value for proof_mat_type.mat_type_code
     *
     * @mbggenerated
     */
    public void setMatTypeCode(String matTypeCode) {
        this.matTypeCode = matTypeCode == null ? null : matTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat_type.use_scope
     *
     * @return the value of proof_mat_type.use_scope
     *
     * @mbggenerated
     */
    public String getUseScope() {
        return useScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat_type.use_scope
     *
     * @param useScope the value for proof_mat_type.use_scope
     *
     * @mbggenerated
     */
    public void setUseScope(String useScope) {
        this.useScope = useScope == null ? null : useScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat_type.create_user_uuid
     *
     * @return the value of proof_mat_type.create_user_uuid
     *
     * @mbggenerated
     */
    public String getCreateUserUuid() {
        return createUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat_type.create_user_uuid
     *
     * @param createUserUuid the value for proof_mat_type.create_user_uuid
     *
     * @mbggenerated
     */
    public void setCreateUserUuid(String createUserUuid) {
        this.createUserUuid = createUserUuid == null ? null : createUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat_type.create_time
     *
     * @return the value of proof_mat_type.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat_type.create_time
     *
     * @param createTime the value for proof_mat_type.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat_type.last_update_user_uuid
     *
     * @return the value of proof_mat_type.last_update_user_uuid
     *
     * @mbggenerated
     */
    public String getLastUpdateUserUuid() {
        return lastUpdateUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat_type.last_update_user_uuid
     *
     * @param lastUpdateUserUuid the value for proof_mat_type.last_update_user_uuid
     *
     * @mbggenerated
     */
    public void setLastUpdateUserUuid(String lastUpdateUserUuid) {
        this.lastUpdateUserUuid = lastUpdateUserUuid == null ? null : lastUpdateUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat_type.last_update_time
     *
     * @return the value of proof_mat_type.last_update_time
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat_type.last_update_time
     *
     * @param lastUpdateTime the value for proof_mat_type.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat_type.del_flag
     *
     * @return the value of proof_mat_type.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat_type.del_flag
     *
     * @param delFlag the value for proof_mat_type.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}