package test.model;

import java.util.Date;

public class ProofMat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat.proof_mat_id
     *
     * @mbggenerated
     */
    private Integer proofMatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat.proof_mat_uuid
     *
     * @mbggenerated
     */
    private String proofMatUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat.provider_uuid
     *
     * @mbggenerated
     */
    private String providerUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat.proof_mat_type_uuid
     *
     * @mbggenerated
     */
    private String proofMatTypeUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat.party_uuid
     *
     * @mbggenerated
     */
    private String partyUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat.property_uuid
     *
     * @mbggenerated
     */
    private String propertyUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat.mat_type_code
     *
     * @mbggenerated
     */
    private String matTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat.mat_name
     *
     * @mbggenerated
     */
    private String matName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat.mat_url
     *
     * @mbggenerated
     */
    private String matUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat.user_filename
     *
     * @mbggenerated
     */
    private String userFilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat.tencent_file_id
     *
     * @mbggenerated
     */
    private String tencentFileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat.create_user_uuid
     *
     * @mbggenerated
     */
    private String createUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat.last_update_user_uuid
     *
     * @mbggenerated
     */
    private String lastUpdateUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat.last_update_time
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proof_mat.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat.proof_mat_id
     *
     * @return the value of proof_mat.proof_mat_id
     *
     * @mbggenerated
     */
    public Integer getProofMatId() {
        return proofMatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat.proof_mat_id
     *
     * @param proofMatId the value for proof_mat.proof_mat_id
     *
     * @mbggenerated
     */
    public void setProofMatId(Integer proofMatId) {
        this.proofMatId = proofMatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat.proof_mat_uuid
     *
     * @return the value of proof_mat.proof_mat_uuid
     *
     * @mbggenerated
     */
    public String getProofMatUuid() {
        return proofMatUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat.proof_mat_uuid
     *
     * @param proofMatUuid the value for proof_mat.proof_mat_uuid
     *
     * @mbggenerated
     */
    public void setProofMatUuid(String proofMatUuid) {
        this.proofMatUuid = proofMatUuid == null ? null : proofMatUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat.provider_uuid
     *
     * @return the value of proof_mat.provider_uuid
     *
     * @mbggenerated
     */
    public String getProviderUuid() {
        return providerUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat.provider_uuid
     *
     * @param providerUuid the value for proof_mat.provider_uuid
     *
     * @mbggenerated
     */
    public void setProviderUuid(String providerUuid) {
        this.providerUuid = providerUuid == null ? null : providerUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat.proof_mat_type_uuid
     *
     * @return the value of proof_mat.proof_mat_type_uuid
     *
     * @mbggenerated
     */
    public String getProofMatTypeUuid() {
        return proofMatTypeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat.proof_mat_type_uuid
     *
     * @param proofMatTypeUuid the value for proof_mat.proof_mat_type_uuid
     *
     * @mbggenerated
     */
    public void setProofMatTypeUuid(String proofMatTypeUuid) {
        this.proofMatTypeUuid = proofMatTypeUuid == null ? null : proofMatTypeUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat.party_uuid
     *
     * @return the value of proof_mat.party_uuid
     *
     * @mbggenerated
     */
    public String getPartyUuid() {
        return partyUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat.party_uuid
     *
     * @param partyUuid the value for proof_mat.party_uuid
     *
     * @mbggenerated
     */
    public void setPartyUuid(String partyUuid) {
        this.partyUuid = partyUuid == null ? null : partyUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat.property_uuid
     *
     * @return the value of proof_mat.property_uuid
     *
     * @mbggenerated
     */
    public String getPropertyUuid() {
        return propertyUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat.property_uuid
     *
     * @param propertyUuid the value for proof_mat.property_uuid
     *
     * @mbggenerated
     */
    public void setPropertyUuid(String propertyUuid) {
        this.propertyUuid = propertyUuid == null ? null : propertyUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat.mat_type_code
     *
     * @return the value of proof_mat.mat_type_code
     *
     * @mbggenerated
     */
    public String getMatTypeCode() {
        return matTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat.mat_type_code
     *
     * @param matTypeCode the value for proof_mat.mat_type_code
     *
     * @mbggenerated
     */
    public void setMatTypeCode(String matTypeCode) {
        this.matTypeCode = matTypeCode == null ? null : matTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat.mat_name
     *
     * @return the value of proof_mat.mat_name
     *
     * @mbggenerated
     */
    public String getMatName() {
        return matName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat.mat_name
     *
     * @param matName the value for proof_mat.mat_name
     *
     * @mbggenerated
     */
    public void setMatName(String matName) {
        this.matName = matName == null ? null : matName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat.mat_url
     *
     * @return the value of proof_mat.mat_url
     *
     * @mbggenerated
     */
    public String getMatUrl() {
        return matUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat.mat_url
     *
     * @param matUrl the value for proof_mat.mat_url
     *
     * @mbggenerated
     */
    public void setMatUrl(String matUrl) {
        this.matUrl = matUrl == null ? null : matUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat.user_filename
     *
     * @return the value of proof_mat.user_filename
     *
     * @mbggenerated
     */
    public String getUserFilename() {
        return userFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat.user_filename
     *
     * @param userFilename the value for proof_mat.user_filename
     *
     * @mbggenerated
     */
    public void setUserFilename(String userFilename) {
        this.userFilename = userFilename == null ? null : userFilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat.tencent_file_id
     *
     * @return the value of proof_mat.tencent_file_id
     *
     * @mbggenerated
     */
    public String getTencentFileId() {
        return tencentFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat.tencent_file_id
     *
     * @param tencentFileId the value for proof_mat.tencent_file_id
     *
     * @mbggenerated
     */
    public void setTencentFileId(String tencentFileId) {
        this.tencentFileId = tencentFileId == null ? null : tencentFileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat.create_user_uuid
     *
     * @return the value of proof_mat.create_user_uuid
     *
     * @mbggenerated
     */
    public String getCreateUserUuid() {
        return createUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat.create_user_uuid
     *
     * @param createUserUuid the value for proof_mat.create_user_uuid
     *
     * @mbggenerated
     */
    public void setCreateUserUuid(String createUserUuid) {
        this.createUserUuid = createUserUuid == null ? null : createUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat.create_time
     *
     * @return the value of proof_mat.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat.create_time
     *
     * @param createTime the value for proof_mat.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat.last_update_user_uuid
     *
     * @return the value of proof_mat.last_update_user_uuid
     *
     * @mbggenerated
     */
    public String getLastUpdateUserUuid() {
        return lastUpdateUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat.last_update_user_uuid
     *
     * @param lastUpdateUserUuid the value for proof_mat.last_update_user_uuid
     *
     * @mbggenerated
     */
    public void setLastUpdateUserUuid(String lastUpdateUserUuid) {
        this.lastUpdateUserUuid = lastUpdateUserUuid == null ? null : lastUpdateUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat.last_update_time
     *
     * @return the value of proof_mat.last_update_time
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat.last_update_time
     *
     * @param lastUpdateTime the value for proof_mat.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proof_mat.del_flag
     *
     * @return the value of proof_mat.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proof_mat.del_flag
     *
     * @param delFlag the value for proof_mat.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}