package test.dao;

import test.model.FinancIncomeDomain;

public interface FinancIncomeDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financ_income
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer financIncomeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financ_income
     *
     * @mbggenerated
     */
    int insert(FinancIncomeDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financ_income
     *
     * @mbggenerated
     */
    int insertSelective(FinancIncomeDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financ_income
     *
     * @mbggenerated
     */
    FinancIncomeDomain selectByPrimaryKey(Integer financIncomeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financ_income
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FinancIncomeDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financ_income
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FinancIncomeDomain record);
}