package test.dao;

import test.model.PartyDomain;

public interface PartyDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer partyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated
     */
    int insert(PartyDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated
     */
    int insertSelective(PartyDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated
     */
    PartyDomain selectByPrimaryKey(Integer partyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PartyDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PartyDomain record);
}