package test.dao;

import test.model.PartyOrgDomain;

public interface PartyOrgDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_org
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer partyOrgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_org
     *
     * @mbggenerated
     */
    int insert(PartyOrgDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_org
     *
     * @mbggenerated
     */
    int insertSelective(PartyOrgDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_org
     *
     * @mbggenerated
     */
    PartyOrgDomain selectByPrimaryKey(Integer partyOrgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_org
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PartyOrgDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_org
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PartyOrgDomain record);
}