package test.dao;

import test.model.PartyVisitLogDomain;

public interface PartyVisitLogDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_visit_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer partyVisitLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_visit_log
     *
     * @mbggenerated
     */
    int insert(PartyVisitLogDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_visit_log
     *
     * @mbggenerated
     */
    int insertSelective(PartyVisitLogDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_visit_log
     *
     * @mbggenerated
     */
    PartyVisitLogDomain selectByPrimaryKey(Integer partyVisitLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_visit_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PartyVisitLogDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_visit_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PartyVisitLogDomain record);
}