package test.dao;

import test.model.ProductOrderDomain;

public interface ProductOrderDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer productOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated
     */
    int insert(ProductOrderDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated
     */
    int insertSelective(ProductOrderDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated
     */
    ProductOrderDomain selectByPrimaryKey(Integer productOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductOrderDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductOrderDomain record);
}