package test.dao;

import test.model.ProofMat;

public interface ProofMatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proof_mat
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer proofMatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proof_mat
     *
     * @mbggenerated
     */
    int insert(ProofMat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proof_mat
     *
     * @mbggenerated
     */
    int insertSelective(ProofMat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proof_mat
     *
     * @mbggenerated
     */
    ProofMat selectByPrimaryKey(Integer proofMatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proof_mat
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProofMat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proof_mat
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProofMat record);
}