package test.dao;

import test.model.ProofMatType;

public interface ProofMatTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proof_mat_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer proofMatTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proof_mat_type
     *
     * @mbggenerated
     */
    int insert(ProofMatType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proof_mat_type
     *
     * @mbggenerated
     */
    int insertSelective(ProofMatType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proof_mat_type
     *
     * @mbggenerated
     */
    ProofMatType selectByPrimaryKey(Integer proofMatTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proof_mat_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProofMatType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proof_mat_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProofMatType record);
}